
services:
  web-app:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_URI=mongodb+srv://sal9791:haikufinalpush@haiku.b73rvtd.mongodb.net/?retryWrites=true&w=majority&appName=haiku
      - MONGO_DB=haiku
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_URI=mongodb+srv://sal9791:haikufinalpush@haiku.b73rvtd.mongodb.net/?retryWrites=true&w=majority&appName=haiku
      - MONGO_DB=haiku
    volumes:
      - type: bind
        source: ./data
        target: /data/db


