
services:
  web-app:
    build: ./web-app
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb+srv://sal9791:haikufinalpush@haiku.b73rvtd.mongodb.net/?retryWrites=true&w=majority&appName=haiku
      - MONGO_DB=haiku
    networks:
      - app_network
  
networks:
  app_network:
    driver: bridge
