version: "3.9"

services:
  web-app:
    build: ./web-app
    container_name: web-app
    ports:
      - "5001:5001"
    env_file:
      - ./web-app/.env  # contains your MONGO_URI for Atlas
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
