
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - app_network

  web-app:
    build: ./web-app
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
    depends_on:
      - mongodb
    networks:
      - app_network
  
networks:
  app_network:
    driver: bridge
